### ISSUE TITLE
Rewrite with Jekyll

### ISSUE THREAD

**Issue by ErikBjare** [Code-at-LTH/code-at-lth.github.io#2]
In order to serve pages easily which can be updated (almost) instantly.

When this is done the following issues may be added:
- Implement proper blog posts
- Add "About" page
- Add "Resources" page (with a better name?)
- More (suggestions please)

**Comment by velixo** [comment]
Suggestion: Add a page where people can post their projects (github or other links) and provide a description if they wish

This open source project database could go under Subpage 2?

**Comment by ErikBjare** [comment]
@velixo That might be something to do when we have the basics now. People won't be able to "post" their projects due to the static nature of the site, but they could always make a pull request to the repo.

Finished the rewrite, closing.
